source("E:/R/AML_4/package.r")
source("E:/R/AML_4/load_kyc.r")
source("E:/R/AML_4/load_tran.r")
source("E:/R/AML_4/kyc_clustering.r")
source("E:/R/AML_4/tran_clustering.r")
source("E:/R/AML_4/sort.r")
source("E:/R/AML_4/compare.r")
source("E:/R/AML_4/fill_alerts.r")