source("J:/R/AML_3/package.r")
source("J:/R/AML_3/load_kyc.r")
source("J:/R/AML_3/load_tran.r")
source("J:/R/AML_3/kyc_clustering.r")
source("J:/R/AML_3/tran_clustering.r")
source("J:/R/AML_3/sort.r")
source("J:/R/AML_3/compare.r")
source("J:/R/AML_3/fill_alerts.r")